# Generated by Django 6.0.2 on 2026-05-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0002_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_highlight', models.CharField(max_length=100)),
                ('banner_page_name', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(upload_to='contact/banner/')),
                ('form_small_title', models.CharField(max_length=100)),
                ('form_title', models.CharField(max_length=100)),
                ('form_highlight', models.CharField(max_length=100)),
                ('form_description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('location_small_title', models.CharField(max_length=100)),
                ('location_title', models.CharField(max_length=100)),
                ('location_highlight', models.CharField(max_length=100)),
                ('location_description', models.TextField()),
                ('map_url', models.TextField()),
                ('direction_url', models.URLField()),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='school',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
