# Generated by Django 6.0.2 on 2026-05-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0004_school_student_delete_contactinfo_delete_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_item', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HOME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loader_logo', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_logo', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
