# Generated by Django 6.0.2 on 2026-05-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0006_contactinfo_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOOTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_heading', models.CharField()),
                ('footer_detail', models.CharField()),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('timing', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FOOTERINFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_logo', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_line', models.CharField(blank=True, max_length=200, null=True)),
                ('footer_bottom', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
