# Generated by Django 6.0.2 on 2026-05-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0007_footer_footercontact_footerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_info_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('form_info_label', models.CharField(blank=True, max_length=200, null=True)),
                ('form_info_value', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_section_label', models.CharField(blank=True, max_length=200, null=True)),
                ('res_section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('res_section_divider_left', models.CharField(blank=True, max_length=200, null=True)),
                ('font_family', models.CharField(blank=True, max_length=200, null=True)),
                ('text_muted', models.CharField(blank=True, max_length=200, null=True)),
                ('resName', models.CharField(blank=True, max_length=200, null=True)),
                ('resEmail', models.CharField(blank=True, max_length=200, null=True)),
                ('resPhone', models.CharField(blank=True, max_length=200, null=True)),
                ('resGuests', models.CharField(blank=True, max_length=200, null=True)),
                ('resDate', models.CharField(blank=True, max_length=200, null=True)),
                ('resTime', models.CharField(blank=True, max_length=200, null=True)),
                ('resRequest', models.CharField(blank=True, max_length=200, null=True)),
                ('res_submit', models.CharField(blank=True, max_length=200, null=True)),
                ('res_success_message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
