# Generated by Django 6.0.2 on 2026-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0008_resdetail_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heritage_section_label', models.CharField(blank=True, max_length=200, null=True)),
                ('heritage_section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('heritage_title_highlight', models.CharField(blank=True, max_length=200, null=True)),
                ('heritage_description', models.TextField(blank=True, null=True)),
                ('heritage_image', models.ImageField(blank=True, null=True, upload_to='about/heritage/')),
                ('heritage_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('heritage_button_url', models.CharField(blank=True, default='reservation.html', max_length=200, null=True)),
                ('quote', models.CharField(blank=True, max_length=300, null=True)),
                ('quote_author', models.CharField(blank=True, max_length=200, null=True)),
                ('mv_section_label', models.CharField(blank=True, max_length=200, null=True)),
                ('mv_section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('mv_title_highlight', models.CharField(blank=True, max_length=200, null=True)),
                ('chef_section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('chef_section_highlight', models.CharField(blank=True, max_length=200, null=True)),
                ('chef_section_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/chefs/')),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Bootstrap icon class, e.g. bi bi-heart-fill', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mission & Value',
                'verbose_name_plural': 'Missions & Values',
                'ordering': ['order'],
            },
        ),
    ]
