# Generated by Django 6.0.2 on 2026-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0009_aboutpage_chef_missionvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='index/dishes/')),
                ('badge', models.CharField(blank=True, help_text="e.g. Chef's Pick, Signature", max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Featured Dish',
                'verbose_name_plural': 'Featured Dishes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IndexAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_num', models.CharField(max_length=10)),
                ('badge_text', models.CharField(help_text='Text inside the year badge', max_length=100)),
                ('main_image', models.ImageField(upload_to='index/about/')),
                ('accent_image', models.ImageField(upload_to='index/about/')),
                ('label', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('title_highlight', models.CharField(max_length=100)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
            ],
            options={
                'verbose_name': 'Index About Section',
            },
        ),
        migrations.CreateModel(
            name='IndexCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('btn_text', models.CharField(default='Book a Table', max_length=100)),
                ('btn_url', models.CharField(default='reservation.html', max_length=200)),
            ],
            options={
                'verbose_name': 'Index CTA Banner',
            },
        ),
        migrations.CreateModel(
            name='IndexHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Est. 1998 · Roma, Italia', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('title_italic', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='index/hero/')),
                ('btn1_text', models.CharField(default='View Our Menu', max_length=100)),
                ('btn1_url', models.CharField(default='menu.html', max_length=200)),
                ('btn2_text', models.CharField(default='Book a Table', max_length=100)),
                ('btn2_url', models.CharField(default='reservation.html', max_length=200)),
            ],
            options={
                'verbose_name': 'Index Hero',
                'verbose_name_plural': 'Index Hero',
            },
        ),
        migrations.CreateModel(
            name='IndexStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_number', models.IntegerField(help_text='The number to animate to')),
                ('suffix', models.CharField(blank=True, help_text='e.g. +, k+', max_length=10, null=True)),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Index Stat',
                'verbose_name_plural': 'Index Stats',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IndexTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_title', models.CharField(max_length=100)),
                ('author_image', models.ImageField(upload_to='index/testimonials/')),
                ('stars', models.PositiveIntegerField(default=5, help_text='Number of stars (1-5)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Index Testimonial',
                'verbose_name_plural': 'Index Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'Contact Page'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='header',
            name='remarks',
        ),
        migrations.AddField(
            model_name='header',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='header',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='chef',
            name='instagram_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='linkedin_url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_detail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='footer',
            name='footer_heading',
            field=models.CharField(max_length=200),
        ),
    ]
