# Generated by Django 6.0.2 on 2026-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0011_menucategory_menupage_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_highlight', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='signup/banner/')),
            ],
        ),
    ]
