# Generated by Django 6.0.2 on 2026-05-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0014_staffattendance_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='category',
            field=models.CharField(choices=[('Regular', 'Regular'), ('VIP', 'VIP'), ('Family', 'Family')], default='Regular', max_length=50),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Reserved', 'Reserved')], default='Pending', max_length=20),
        ),
    ]
