# Generated by Django 6.0.2 on 2026-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0015_restauranttable_category_restauranttable_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffattendance',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
