# Generated by Django 6.0.2 on 2026-05-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paradox', '0016_staffattendance_is_logged_in'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together=set(),
        ),
    ]
